[package]
name = "think_bayes"
version = "0.1.0"
authors = ["Jacob Finkelman <Eh2406@wayne.edu>"]

[dependencies]
fnv = "1.0"
rand = "0.3"
itertools = "0.4.15"

[dev-dependencies]
approx = "0.1.0"
quickcheck = "0.2.27"
